services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"

      # 根域名真正提供服务（HTTP → HTTPS）
      - "traefik.http.middlewares.to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.root-http.rule=Host(`luolink.com`)"
      - "traefik.http.routers.root-http.entrypoints=web"
      - "traefik.http.routers.root-http.middlewares=to-https"
      - "traefik.http.routers.root-https.rule=Host(`luolink.com`)"
      - "traefik.http.routers.root-https.entrypoints=websecure"
      - "traefik.http.routers.root-https.tls=true"
      - "traefik.http.routers.root-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.root-svc.loadbalancer.server.port=3000"

      # www.luolink.com → https://luolink.com (301)
      - "traefik.http.middlewares.www2root.redirectregex.regex=^https?://www\\.luolink\\.com/(.*)"
      - "traefik.http.middlewares.www2root.redirectregex.replacement=https://luolink.com/$1"
      - "traefik.http.middlewares.www2root.redirectregex.permanent=true"

      # 为 www 建两个只做重定向的路由（80/443）
      - "traefik.http.routers.www-redirect-web.rule=Host(`www.luolink.com`)"
      - "traefik.http.routers.www-redirect-web.entrypoints=web"
      - "traefik.http.routers.www-redirect-web.middlewares=www2root"
      - "traefik.http.routers.www-redirect-web.service=noop@internal"

      - "traefik.http.routers.www-redirect-websecure.rule=Host(`www.luolink.com`)"
      - "traefik.http.routers.www-redirect-websecure.entrypoints=websecure"
      - "traefik.http.routers.www-redirect-websecure.tls=true"
      - "traefik.http.routers.www-redirect-websecure.middlewares=www2root"
      - "traefik.http.routers.www-redirect-websecure.service=noop@internal"
